# ClusterRole for node-setup-daemonset.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-setup-daemonset
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - apps
      - extensions
    resources:
      - daemonsets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
  - apiGroups:
      - scylla.scylladb.com
    resources:
      - scyllaclusters
    verbs:
      - get
      - list
      - watch
---
# ServiceAccount for node-setup daemonset.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-setup-daemonset
  namespace: default
---
# Bind node-setup daemonset ServiceAccount with ClusterRole.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-setup-daemonset
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-setup-daemonset
subjects:
- kind: ServiceAccount
  name: node-setup-daemonset
  namespace: default
---
# Daemonset that will change cpuManagerPolicy to static.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cpu-policy
spec:
  selector:
    matchLabels:
      name: cpu-policy
  template:
    metadata:
      labels:
        name: cpu-policy
    spec:
      hostPID: true
      hostIPC: true
      serviceAccountName: node-setup-daemonset
      containers:
      - name: cpu-policy
        image: bitnami/kubectl:1.21.4
        imagePullPolicy: Always
        env:
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: HOSTFS
            value: /mnt/hostfs
          - name: KUBELET_CONFIG_PATH
            value: /etc/kubernetes/kubelet/kubelet-config.json
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
          - name: hostfs
            mountPath: /mnt/hostfs
            mountPropagation: Bidirectional
        command:
          - "/bin/bash"
          - "-c"
          - "--"
        args:
          - |
            set -ex
            if [ ! -f "$HOSTFS$KUBELET_CONFIG_PATH" ]; then
                echo "Kublet config not found"
                exit 1
            fi

            TOKEN_PATH=$(find /run/secrets/kubernetes.io -name token | grep token -m1)
            TOKEN=$(cat $TOKEN_PATH)
            CA_CRT=$TOKEN_PATH/../ca.crt
            kubectl config set-cluster scylla --server=https://kubernetes.default --certificate-authority=$CA_CRT
            kubectl config set-credentials qa@scylladb.com --token=$TOKEN
            kubectl config set-context scylla --cluster=scylla --user=qa@scylladb.com
            kubectl config use-context scylla

            if grep "cpuManagerPolicy" $HOSTFS$KUBELET_CONFIG_PATH | grep "static" ; then
                echo "cpu-manager-policy is already set to be static"
                echo "uncordoning the node"
                kubectl uncordon $NODE || true
                while true; do sleep infinity; done
            fi

            echo "Change kubelet config and restart it's service"
            kubectl drain $NODE --force --ignore-daemonsets --delete-local-data --grace-period=60
            awk 'NR==2{print "  \"cpuManagerPolicy\": \"static\","}1' $HOSTFS$KUBELET_CONFIG_PATH > \
                tmp-kubelet-config.json && cat tmp-kubelet-config.json > $HOSTFS$KUBELET_CONFIG_PATH
            rm $HOSTFS/var/lib/kubelet/cpu_manager_state
            kill -9 $(pidof kubelet)
      volumes:
        - name: hostfs
          hostPath:
            path: /
        - name: dbus
          hostPath:
            path: /var/run/dbus
        - name: systemd
          hostPath:
            path: /run/systemd
        - name: systemctl
          hostPath:
            path: /bin/systemctl
        - name: system
          hostPath:
            path: /etc/systemd/system
        - name: usr
          hostPath:
            path: /usr
        - name: lib
          hostPath:
            path: /lib/systemd
        - name: lib-linux
          hostPath:
            path: /lib/systemd
---
# NOTE: 'node-pkg-installer' is taken from here:
# https://github.com/scylladb/scylla-operator/commit/fa09b328c9c6aabded912a98f2a7aadad74d07e4
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-pkg-installer
  labels:
    app: node-pkg-installer
spec:
  selector:
    matchLabels:
      app: node-pkg-installer
  template:
    metadata:
      labels:
        app: node-pkg-installer
    spec:
      containers:
      # NOTE: image is built on Feb 1, 2023 -> scylla-operator:1.9.0-alpha.1
      - image: "scylladb/scylla-operator@sha256:10e3e7dddc2de1bbd473710223a4be5e8c5ef5dc9bb1a61d81fdc398d9dcd74c"
        imagePullPolicy: "Always"
        name: node-pkg-installer
        command:
        - "/usr/sbin/chroot"
        - "/host"
        - "/usr/bin/bash"
        - "-euExo"
        - "pipefail"
        - "-c"
        args:
        - |
          yum install -y util-linux xfsprogs mdadm && \
          sleep infinity
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: hostfs
      volumes:
      - name: hostfs
        hostPath:
          path: /
---
# Daemonset that will configure disks and networking interfaces on node.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-setup
spec:
  selector:
    matchLabels:
      name: node-setup
  template:
    metadata:
      labels:
        name: node-setup
    spec:
      hostPID: true
      hostIPC: true
      serviceAccountName: node-setup-daemonset
      containers:
      - name: node-setup
        image: scylladb/scylla-machine-image:k8s-aws-666.development-20201023.0c4dfa1
        imagePullPolicy: Always
        env:
          - name: ROOT_DISK
            value: /mnt/hostfs/mnt/raid-disks/disk0
          - name: SCYLLAD_CONF_MOUNT
            value: /mnt/scylla.d/
        command:
          - "/bin/bash"
          - "-c"
          - "--"
        args:
          - |
            # NOTE: following is needed to avoid package installation failures caused
            #       by the absent scylla package repositories.
            yum-config-manager --disable scylla --disable scylla-generic --disable scylladb-scylla-3rdparty
            # NOTE: 'args' will be updated in the code
            #        when perf tuning is disabled it is ['--all']
            #        when perf tuning is enabled it is ['--setup-disks']
            /opt/scylladb/scylla-machine-image/scylla_k8s_node_setup ${SCYLLA_MACHINE_IMAGE_ARGS}
        securityContext:
          privileged: true
        volumeMounts:
          - name: hostfs
            mountPath: /mnt/hostfs
            mountPropagation: Bidirectional
          - name: hostetcscyllad
            mountPath: /mnt/scylla.d
            mountPropagation: Bidirectional
          - name: hostirqbalanceconfig
            mountPath: /etc/conf.d/irqbalance
            mountPropagation: Bidirectional
      - name: pv-setup
        image: bitnami/kubectl:1.21.4
        imagePullPolicy: Always
        env:
          - name: HOSTFS
            value: /mnt/hostfs
          - name: KUBELET_CONFIG_PATH
            value: /etc/kubernetes/kubelet/kubelet-config.json
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
          - name: hostfs
            mountPath: /mnt/hostfs
            mountPropagation: Bidirectional
        command:
          - "/bin/bash"
          - "-c"
          - "--"
        args:
          - |
            set -ex
            if [ ! -f "$HOSTFS$KUBELET_CONFIG_PATH" ]; then
                echo "Kublet config not found"
                exit 1
            fi

            TOKEN_PATH=$(find /run/secrets/kubernetes.io -name token | grep token -m1)
            TOKEN=$(cat $TOKEN_PATH)
            CA_CRT=$TOKEN_PATH/../ca.crt
            kubectl config set-cluster scylla --server=https://kubernetes.default --certificate-authority=$CA_CRT
            kubectl config set-credentials qa@scylladb.com --token=$TOKEN
            kubectl config set-context scylla --cluster=scylla --user=qa@scylladb.com
            kubectl config use-context scylla

            # Create directories for each Scylla cluster on each K8S node which will host PVs
            while true; do
              DEVICE_PATH=$(mount | grep "raid-disks/disk0 " | awk '{print $1;}')
              if [[ -z $DEVICE_PATH ]]; then
                sleep 5;
                continue
              fi
              for i in $(seq -f "pv-%02g" $( kubectl get scyllaclusters -A --field-selector metadata.name!=scylla-manager --no-headers | grep -c " " ) ); do
                if [[ ! -d "/mnt/hostfs/mnt/raid-disks/disk0/${i}" ]]; then
                  mkdir "/mnt/hostfs/mnt/raid-disks/disk0/${i}"
                fi
                ( mount | grep "/mnt/hostfs/mnt/raid-disks/disk0/${i} " 2>/dev/null 1>&2 ) || \
                mount --bind "/mnt/hostfs/mnt/raid-disks/disk0/${i}"{,}
              done
              sleep 10
            done
      volumes:
        - name: hostfs
          hostPath:
            path: /
        - name: hostetcscyllad
          hostPath:
            path: /etc/scylla.d/
        - name: hostirqbalanceconfig
          hostPath:
            path: /etc/sysconfig/irqbalance
