pull_request_rules:
  - name: put PR in draft if conflicts
    conditions:
      - label = conflicts
      - author = mergify[bot]
    actions:
      edit:
         draft: true
  - name: Automate backport pull request 6.0
    conditions:
      - base=master # Ensure this rule only applies to PRs merged into the master branch
      - label=backport/6.0 # The PR must have this label to trigger the backport
    actions:
      backport:
        title: "[Backport 6.0] {{ title }}"
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}

          Parent PR: #{{number}}
        branches:
          - branch-6.0
        assignees:
          - "{{ author }}"
  - name: Automate backport pull request 6.1
    conditions:
      - base=master # Ensure this rule only applies to PRs merged into the master branch
      - label=backport/6.1 # The PR must have this label to trigger the backport
    actions:
      backport:
        title: "[Backport 6.1] {{ title }}"
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}

          Parent PR: #{{number}}
        branches:
          - branch-6.1
        assignees:
          - "{{ author }}"
  - name: Automate backport pull request 6.2
    conditions:
      - base=master # Ensure this rule only applies to PRs merged into the master branch
      - label=backport/6.2 # The PR must have this label to trigger the backport
    actions:
      backport:
        title: "[Backport 6.2] {{ title }}"
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}

          Parent PR: #{{number}}
        branches:
          - branch-6.2
        assignees:
          - "{{ author }}"
  - name: Automate backport pull request 2023.1
    conditions:
      - base=master # Ensure this rule only applies to PRs merged into the master branch
      - label=backport/2023.1 # The PR must have this label to trigger the backport
    actions:
      backport:
        title: "[Backport 2023.1] {{ title }}"
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }} )
          {% endfor %}

          Parent PR: #{{number}}
        branches:
          - branch-2023.1
        assignees:
          - "{{ author }}"
  - name: Automate backport pull request 2024.1
    conditions:
      - base=master # Ensure this rule only applies to PRs merged into the master branch
      - label=backport/2024.1 # The PR must have this label to trigger the backport
    actions:
      backport:
        title: "[Backport 2024.1] {{ title }}"
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}

          Parent PR: #{{number}}
        branches:
          - branch-2024.1
        assignees:
          - "{{ author }}"
  - name: Automate backport pull request 2024.2
    conditions:
      - base=master # Ensure this rule only applies to PRs merged into the master branch
      - label=backport/2024.2 # The PR must have this label to trigger the backport
    actions:
      backport:
        title: "[Backport 2024.2] {{ title }}"
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}

          Parent PR: #{{number}}
        branches:
          - branch-2024.2
        assignees:
          - "{{ author }}"
  - name: Automate backport pull request perf-v14
    conditions:
      - base=master # Ensure this rule only applies to PRs merged into the master branch
      - label=backport/perf-v14 # The PR must have this label to trigger the backport
    actions:
      backport:
        title: "[Backport perf-v14] {{ title }}"
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}

          Parent PR: #{{number}}
        branches:
          - branch-perf-v14
        assignees:
          - "{{ author }}"
  - name: Automate backport pull request perf-v15
    conditions:
      - base=master # Ensure this rule only applies to PRs merged into the master branch
      - label=backport/perf-v15 # The PR must have this label to trigger the backport
    actions:
      backport:
        title: "[Backport perf-v15] {{ title }}"
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}

          Parent PR: #{{number}}
        branches:
          - branch-perf-v15
        assignees:
          - "{{ author }}"
  - name: Automate backport pull request perf-v16
    conditions:
      - base=master # Ensure this rule only applies to PRs merged into the master branch
      - label=backport/perf-v16 # The PR must have this label to trigger the backport
    actions:
      backport:
        title: "[Backport perf-v16] {{ title }}"
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}

          Parent PR: #{{number}}
        branches:
          - branch-perf-v16
        assignees:
          - "{{ author }}"
  - name: Automate backport pull request manager-3.2
    conditions:
      - base=master # Ensure this rule only applies to PRs merged into the master branch
      - label=backport/manager-3.2 # The PR must have this label to trigger the backport
    actions:
      backport:
        title: "[Backport manager-3.2] {{ title }}"
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}

          Parent PR: #{{number}}
        branches:
          - manager-3.2
        assignees:
          - "{{ author }}"
  - name: Automate backport pull request manager-3.3
    conditions:
      - base=master # Ensure this rule only applies to PRs merged into the master branch
      - label=backport/manager-3.3 # The PR must have this label to trigger the backport
    actions:
      backport:
        title: "[Backport manager-3.3] {{ title }}"
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}

          Parent PR: #{{number}}
        branches:
          - manager-3.3
        assignees:
          - "{{ author }}"
