cluster_backend: azure
user_prefix: unit-test
instance_provision: 'spot'
instance_provision_fallback_on_demand: false
enterprise_disable_kms: true

azure_instance_type_db: 'Standard_L8s_v3'
azure_instance_type_loader: 'Standard_F4s_v2'
azure_instance_type_monitor: 'Standard_D2_v4'
# get images urn's by running: `az vm image list --output table --all --offer CentOS --publisher OpenLogic`
azure_image_loader: 'OpenLogic:CentOS:7_9:latest'
azure_image_monitor: 'OpenLogic:CentOS:7_9:latest'

availability_zone: 'a'
root_disk_size_monitor: 50  # GB, remove this field if default disk size should be used
root_disk_size_db: 30  # GB, increase root disk for larger swap (maximum: 16G)
root_disk_size_loader: 30  # GB, Increase loader disk in order to have extra space for a larger swap
azure_image_username: 'scyllaadm'
# used prepared centos7 AMI for loader
ami_loader_user: 'centos'
# centos7 is used for monitor
ami_monitor_user: 'centos'
