db_type: "scylla"

test_duration: 60

ip_ssh_connections: 'private'

scylla_repo: ''

manager_version: '3.0'
manager_scylla_backend_version: '2021'  # Notice: that centos, ubuntu 20 and debian 10 monitors use 2021, while debian 9, ubuntu 16 and ubuntu 18 use 2020, since we support both

scylla_repo_loader: 'https://s3.amazonaws.com/downloads.scylladb.com/rpm/centos/scylla-4.6.repo'

experimental: true
round_robin: false

append_scylla_args: '--blocked-reactor-notify-ms 100 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1'
append_scylla_setup_args: ''

db_nodes_shards_selection: 'default'

# for for version selection
scylla_linux_distro: 'ubuntu-focal'
scylla_linux_distro_loader: 'centos'
ssh_transport: 'libssh2'
system_auth_rf: 3

monitor_branch: 'branch-3.10'

space_node_threshold: 0

cluster_health_check: true

add_node_cnt: 1

reuse_cluster: false
nemesis_class_name: 'NoOpMonkey'
nemesis_during_prepare: true
nemesis_interval: 5
nemesis_add_node_cnt: 1

nemesis_filter_seeds: true

seeds_selector: "first"
seeds_num: 1

instance_provision: "spot"

execute_post_behavior: false
post_behavior_db_nodes: "keep-on-failure"
post_behavior_loader_nodes: "destroy"
post_behavior_monitor_nodes: "keep-on-failure"
post_behavior_k8s_cluster: "keep-on-failure"

cloud_credentials_path: '~/.ssh/support'
use_cloud_manager: false
cloud_prom_bearer_token: ''

backtrace_decoding: true
print_kernel_callstack: false

update_db_packages: ''

logs_transport: "syslog-ng"
rsyslog_imjournal_rate_limit_interval: 60  # max. 65535 till rsyslog v8.34
rsyslog_imjournal_rate_limit_burst: 50000  # max. 65535 till rsyslog v8.34

store_perf_results: false
send_email: false
email_recipients: ['qa@scylladb.com']
email_subject_postfix: ''

collect_logs: false

hinted_handoff: 'enabled'

server_encrypt: false
client_encrypt: false

scylla_encryption_options: ''

loader_swap_size: 1024 # Size of swap file for loader node in bytes 1024 * 1MB
monitor_swap_size: 8192 # Size of swap file for monitor node in bytes 8192 * 1MB

compaction_strategy: 'SizeTieredCompactionStrategy'

use_preinstalled_scylla: false

alternator_enforce_authorization: false
alternator_access_key_id: ''
alternator_secret_access_key: ''
dynamodb_primarykey_type: 'HASH'


store_cdclog_reader_stats_in_es: false
region_aware_loader: false

stop_test_on_stress_failure: true

stress_cdc_log_reader_batching_enable: true
use_legacy_cluster_init: false
internode_encryption: 'all'

use_mgmt: true
manager_prometheus_port: 5090
scylla_mgmt_pkg: ''

skip_download: false

authenticator_user: ''
authenticator_password: ''

# gemini defaults
gemini_version: '0.9.2'
n_test_oracle_db_nodes: 1
gemini_seed: 0
oracle_scylla_version: '4.4.7'
append_scylla_args_oracle: '--enable-cache false'

# cassandra-stress defaults
stress_multiplier: 1
keyspace_num: 1
cs_user_profiles: []
cs_duration: '50m'
batch_size: 1
pre_create_schema: false
user_profile_table_count: 1
cassandra_stress_population_size: 1000000
cassandra_stress_threads: 1000

# upgrade params
new_scylla_repo: ''
new_version: ''
upgrade_node_packages: ''
test_sst3: false
authorization_in_upgrade: ''
new_introduced_pkgs: ''
recover_system_tables: false
scylla_version: ''
remove_authorization_in_rollback: false
test_upgrade_from_installed_3_1_0: false
target_upgrade_version: ''

stress_cdclog_reader_cmd: "cdc-stressor -stream-query-round-duration 30s"

jepsen_scylla_repo: 'https://github.com/jepsen-io/scylla.git'
jepsen_test_cmd:
  - 'test-all -w cas-register --concurrency 10n'
  - 'test-all -w counter --concurrency 10n'
  - 'test-all -w cmap --concurrency 10n'
  - 'test-all -w cset --concurrency 10n'
#  - 'test-all -w mv --concurrency 10n'
  - 'test-all -w write-isolation --concurrency 10n'
  - 'test-all -w list-append --concurrency 10n'
  - 'test-all -w wr-register --concurrency 10n'
jepsen_test_count: 1
jepsen_test_run_policy: all

max_events_severities: ""
mgmt_docker_image: ''
k8s_deploy_monitoring: false
k8s_minio_storage_size: '10Gi'

# NOTE: 'k8s_enable_performance_tuning' is alpha feature in operator-1.6 , so it is disabled by default
k8s_enable_performance_tuning: false

# NOTE: if 'k8s_scylla_utils_docker_image' is not specified then default values from operator-1.6+ will be used
k8s_scylla_utils_docker_image: ''

scylla_rsyslog_setup: false

backup_bucket_region: ''  # use the same region as a cluster

events_limit_in_email: 10

scylla_bench_version: v0.1.8

data_volume_disk_num: 0
data_volume_disk_type: ''
data_volume_disk_size: 0
data_volume_disk_iops: 0 # depend on type iops could be 100-16000 for io2|io3 and 3000-16000 for gp3
install_mode: 'repo'  # install from scylla_repo
nosqlbench_image: 'scylladb/hydra-loaders:nosqlbench-4.15.49'
run_db_node_benchmarks: false

nemesis_multiply_factor: 6

scylla_apt_keys:
  - '17723034C56D4B19'  # ScyllaDB Package Signing Key 2018 <security@scylladb.com>
  - '5E08FBD8B5D6EC9C'  # ScyllaDB Package Signing Key 2020 <security@scylladb.com>
  - 'D0A112E067426AB2'  # ScyllaDB Package Signing Key 2022 <security@scylladb.com>

raid_level: 0

bare_loaders: false
