db_type: "scylla"

test_duration: 60
prepare_stress_duration: 300 # 5 hours
stress_duration: 0

ip_ssh_connections: 'private'

scylla_repo: ''

manager_version: '3.1'
manager_scylla_backend_version: '2022'
# Notice: that centos (default monitor), ubuntu 22, ubuntu 20 and debian 11 monitors use 2022, while debian 10 ubuntu 18 use 2021, since we support both

scylla_repo_loader: 'https://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu/scylla-5.2.list'

experimental: true
round_robin: false

append_scylla_args: '--blocked-reactor-notify-ms 25 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1'
append_scylla_setup_args: ''

db_nodes_shards_selection: 'default'

# for for version selection
scylla_linux_distro: 'ubuntu-focal'
scylla_linux_distro_loader: 'ubuntu-jammy'
ssh_transport: 'libssh2'

monitor_branch: 'branch-4.4'

space_node_threshold: 0

cluster_health_check: true

add_node_cnt: 1

reuse_cluster: false
nemesis_class_name: 'NoOpMonkey'
nemesis_during_prepare: true
nemesis_interval: 5
nemesis_add_node_cnt: 1

nemesis_filter_seeds: false

seeds_selector: "all"
seeds_num: 1

instance_provision: "spot"

execute_post_behavior: false
post_behavior_db_nodes: "keep-on-failure"
post_behavior_loader_nodes: "destroy"
post_behavior_monitor_nodes: "keep-on-failure"
post_behavior_k8s_cluster: "keep-on-failure"

cloud_credentials_path: ''
use_cloud_manager: false
cloud_prom_bearer_token: ''

backtrace_decoding: true
print_kernel_callstack: true

update_db_packages: ''

logs_transport: "syslog-ng"
rsyslog_imjournal_rate_limit_interval: 60  # max. 65535 till rsyslog v8.34
rsyslog_imjournal_rate_limit_burst: 50000  # max. 65535 till rsyslog v8.34

store_perf_results: false
send_email: false
email_recipients: ['qa@scylladb.com']
email_subject_postfix: ''

collect_logs: false

hinted_handoff: 'disabled'

server_encrypt: false
client_encrypt: false

scylla_encryption_options: ''

loader_swap_size: 1024 # Size of swap file for loader node in bytes 1024 * 1MB
monitor_swap_size: 8192 # Size of swap file for monitor node in bytes 8192 * 1MB

compaction_strategy: 'SizeTieredCompactionStrategy'

use_preinstalled_scylla: false

alternator_enforce_authorization: false
alternator_access_key_id: ''
alternator_secret_access_key: ''
dynamodb_primarykey_type: 'HASH'


store_cdclog_reader_stats_in_es: false
region_aware_loader: false

stop_test_on_stress_failure: true

stress_cdc_log_reader_batching_enable: true
use_legacy_cluster_init: false
internode_encryption: 'all'

use_mgmt: true
manager_prometheus_port: 5090
scylla_mgmt_pkg: ''

skip_download: false

authenticator_user: ''
authenticator_password: ''

# gemini defaults
n_test_oracle_db_nodes: 1
gemini_seed: 0
oracle_scylla_version: '2021.1.15'
append_scylla_args_oracle: '--enable-cache false'

# cassandra-stress defaults
stress_multiplier: 1
stress_multiplier_w: 1
stress_multiplier_r: 1
stress_multiplier_m: 1
keyspace_num: 1
cs_user_profiles: []
cs_duration: '50m'
batch_size: 1
pre_create_schema: false
user_profile_table_count: 1
cassandra_stress_population_size: 1000000
cassandra_stress_threads: 1000

# upgrade params
new_scylla_repo: ''
new_version: ''
upgrade_node_packages: ''
test_sst3: false
recover_system_tables: false
scylla_version: ''
test_upgrade_from_installed_3_1_0: false
target_upgrade_version: ''
disable_raft: true

stress_cdclog_reader_cmd: "cdc-stressor -stream-query-round-duration 30s"

jepsen_scylla_repo: 'https://github.com/jepsen-io/scylla.git'
jepsen_test_cmd:
  - 'test-all -w cas-register --concurrency 10n'
  - 'test-all -w counter --concurrency 10n'
  - 'test-all -w cmap --concurrency 10n'
  - 'test-all -w cset --concurrency 10n'
#  - 'test-all -w mv --concurrency 10n'
  - 'test-all -w write-isolation --concurrency 10n'
  - 'test-all -w list-append --concurrency 10n'
  - 'test-all -w wr-register --concurrency 10n'
jepsen_test_count: 1
jepsen_test_run_policy: all

max_events_severities: ""
mgmt_docker_image: ''
k8s_log_api_calls: false
k8s_deploy_monitoring: false
k8s_minio_storage_size: '10Gi'
k8s_n_scylla_pods_per_cluster: 3

k8s_loader_run_type: 'dynamic'

k8s_tenants_num: 1

# NOTE: if 'k8s_scylla_utils_docker_image' is not specified then default values from operator-1.6+ will be used
k8s_scylla_utils_docker_image: ''

scylla_rsyslog_setup: false

backup_bucket_region: ''  # use the same region as a cluster

events_limit_in_email: 10

data_volume_disk_num: 0
data_volume_disk_type: ''
data_volume_disk_size: 0
data_volume_disk_iops: 0 # depend on type iops could be 100-16000 for io2|io3 and 3000-16000 for gp3
gce_pd_standard_disk_size_db: 0

install_mode: 'repo'  # install from scylla_repo
run_db_node_benchmarks: false

nemesis_multiply_factor: 6

scylla_apt_keys:
  - '17723034C56D4B19'  # ScyllaDB Package Signing Key 2018 <security@scylladb.com>
  - '5E08FBD8B5D6EC9C'  # ScyllaDB Package Signing Key 2020 <security@scylladb.com>
  - 'D0A112E067426AB2'  # ScyllaDB Package Signing Key 2022 <security@scylladb.com>
  - '491C93B9DE7496A7'  # ScyllaDB Package Signing Key 2024 <security@scylladb.com>

raid_level: 0

bare_loaders: false

nemesis_exclude_disabled: true

aws_fallback_to_next_availability_zone: false

enable_argus: true

stress_image:
  ndbench: 'scylladb/hydra-loaders:ndbench-jdk8-20210720'
  ycsb: 'scylladb/hydra-loaders:ycsb-jdk8-20220918'
  nosqlbench: 'scylladb/hydra-loaders:nosqlbench-4.15.49'
  cassandra-stress: '' # default would be same version as scylla under test
  scylla-bench: 'scylladb/hydra-loaders:scylla-bench-v0.1.18'
  gemini: 'scylladb/hydra-loaders:gemini-v1.8.6'
  alternator-dns: 'scylladb/hydra-loaders:alternator-dns-0.1'
  cdc-stresser: 'scylladb/hydra-loaders:cdc-stresser-20210630'
  kcl: 'scylladb/hydra-loaders:kcl-jdk8-20210526-ShardSyncStrategyType-PERIODIC'
  harry: 'scylladb/hydra-loaders:cassandra-harry-jdk11-20220816'

service_level_shares: [1000]

use_hdr_cs_histogram: false

stop_on_hw_perf_failure: false

custom_es_index: ''

run_fullscan: []

stress_step_duration: '15m'
simulated_racks: 0
