FROM openjdk:8 as builder

ARG BRANCH
ARG GIT_FORK

ENV BRANCH=${BRANCH:-branch-5.0}
ENV GIT_FORK=${GIT_FORK:-https://github.com/scylladb/scylla-tools-java}

RUN git clone -b ${BRANCH} --single-branch ${GIT_FORK}
RUN apt -y update && apt-get -y install ant

# revert of cassandra driver (without shard-aware)
COPY .gitconfig /root/
RUN cd scylla-tools-java && git revert 1deceb8a605e563f01ef1821d48316cea766da31 && git revert 87a98f0a85c9db8a9c7602e66d3d2cca56903cdf

# build
RUN cd scylla-tools-java && ant


FROM openjdk:8 as app

COPY --from=builder /scylla-tools-java /scylla-tools-java

WORKDIR /scylla-tools-java

RUN bash ./SCYLLA-VERSION-GEN \
    && cp build/SCYLLA-* . \
    && ./install.sh

# hack, cause in some versions not all the files are handled by install.sh
RUN find . -iname *.jar | xargs -I{}  cp {} /opt/scylladb/share/cassandra/lib/
