FROM debian:bookworm-slim

ARG DEB_LIST_URL
ARG DEB_KEY

ENV DEB_LIST_URL=${DEB_LIST_URL:-https://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/branch-5.1/deb/unified/2022-08-18T12%3A17%3A46Z/scylladb-5.1/scylla.list}
ENV DEB_KEY=${DEB_KEY:-D0A112E067426AB2}

RUN apt-get update && apt-get -y install wget gnupg2 \
    && wget ${DEB_LIST_URL} \
    && mv scylla.list /etc/apt/sources.list.d/ \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ${DEB_KEY} \
    && gpg --homedir /tmp --no-default-keyring --keyring /etc/apt/keyrings/scylladb.gpg \
    --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys ${DEB_KEY} \
    && apt-get update \
    && apt-get -y install scylla-tools
