#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import (TApplicationException, TException, TMessageType,
                           TType)

from ttypes import *

VERSION = "20.1.0"
