#  pylint:disable=no-self-use,unused-argument,redefined-outer-name,unnecessary-dict-index-lookup

import json
from pathlib import Path
from pprint import pprint
from typing import Generator

import pytest
from assertpy import assert_that, soft_assertions

from sdcm.results_analyze.nosqlbench.analyzer import NoSQLBenchResultsAnalyzer, NoSQLBenchAnalyzerArgs, \
    MetricComparator, ComparisonAxis
from sdcm.results_analyze.nosqlbench.report_builder import NoSQLBenchReportBuilder

NB_SUMMARY_FP = Path("unit_tests/test_data/perf/nosqlbench_summary")
ES_TEST_DOC_FP = Path("unit_tests/test_data/perf/es_test_doc.json")
ES_FILTERED_TEST_RESULTS_FP = Path("unit_tests/test_data/perf/es_filtered_test_results.json")
EXPECTED_FULL_REPORT = {
    'counters': {'main_optracker_blocked': '99902', 'main_pending_ops': '0', 'rampup_optracker_blocked': '9919',
                 'rampup_pending_ops': '0', 'schema_optracker_blocked': '1', 'schema_pending_ops': '0'},
    'histograms': {'main_main_read__main_select__resultset_size_count': '6666',
                   'main_main_read__main_select__resultset_size_min': '0',
                   'main_main_read__main_select__resultset_size_max': '10',
                   'main_main_read__main_select__resultset_size_mean': '5.52',
                   'main_main_read__main_select__resultset_size_stddev': '2.91',
                   'main_main_read__main_select__resultset_size_median': '6.00',
                   'main_main_read__main_select__resultset_size_p75': '8.00',
                   'main_main_read__main_select__resultset_size_p95': '10.00',
                   'main_main_read__main_select__resultset_size_p98': '10.00',
                   'main_main_read__main_select__resultset_size_p99': '10.00',
                   'main_main_read__main_select__resultset_size_p999': '10.00',
                   'main_main_read__main_select_01__resultset_size_count': '6666',
                   'main_main_read__main_select_01__resultset_size_min': '0',
                   'main_main_read__main_select_01__resultset_size_max': '10',
                   'main_main_read__main_select_01__resultset_size_mean': '5.37',
                   'main_main_read__main_select_01__resultset_size_stddev': '2.88',
                   'main_main_read__main_select_01__resultset_size_median': '5.00',
                   'main_main_read__main_select_01__resultset_size_p75': '8.00',
                   'main_main_read__main_select_01__resultset_size_p95': '10.00',
                   'main_main_read__main_select_01__resultset_size_p98': '10.00',
                   'main_main_read__main_select_01__resultset_size_p99': '10.00',
                   'main_main_read__main_select_01__resultset_size_p999': '10.00',
                   'main_main_read__main_select_0123__resultset_size_count': '6666',
                   'main_main_read__main_select_0123__resultset_size_min': '0',
                   'main_main_read__main_select_0123__resultset_size_max': '10',
                   'main_main_read__main_select_0123__resultset_size_mean': '5.41',
                   'main_main_read__main_select_0123__resultset_size_stddev': '2.88',
                   'main_main_read__main_select_0123__resultset_size_median': '5.00',
                   'main_main_read__main_select_0123__resultset_size_p75': '8.00',
                   'main_main_read__main_select_0123__resultset_size_p95': '10.00',
                   'main_main_read__main_select_0123__resultset_size_p98': '10.00',
                   'main_main_read__main_select_0123__resultset_size_p99': '10.00',
                   'main_main_read__main_select_0123__resultset_size_p999': '10.00',
                   'main_main_read__main_select_0246__resultset_size_count': '6666',
                   'main_main_read__main_select_0246__resultset_size_min': '0',
                   'main_main_read__main_select_0246__resultset_size_max': '10',
                   'main_main_read__main_select_0246__resultset_size_mean': '5.44',
                   'main_main_read__main_select_0246__resultset_size_stddev': '2.93',
                   'main_main_read__main_select_0246__resultset_size_median': '6.00',
                   'main_main_read__main_select_0246__resultset_size_p75': '8.00',
                   'main_main_read__main_select_0246__resultset_size_p95': '10.00',
                   'main_main_read__main_select_0246__resultset_size_p98': '10.00',
                   'main_main_read__main_select_0246__resultset_size_p99': '10.00',
                   'main_main_read__main_select_0246__resultset_size_p999': '10.00',
                   'main_main_read__main_select_1357__resultset_size_count': '6666',
                   'main_main_read__main_select_1357__resultset_size_min': '0',
                   'main_main_read__main_select_1357__resultset_size_max': '10',
                   'main_main_read__main_select_1357__resultset_size_mean': '5.31',
                   'main_main_read__main_select_1357__resultset_size_stddev': '2.90',
                   'main_main_read__main_select_1357__resultset_size_median': '5.00',
                   'main_main_read__main_select_1357__resultset_size_p75': '8.00',
                   'main_main_read__main_select_1357__resultset_size_p95': '10.00',
                   'main_main_read__main_select_1357__resultset_size_p98': '10.00',
                   'main_main_read__main_select_1357__resultset_size_p99': '10.00',
                   'main_main_read__main_select_1357__resultset_size_p999': '10.00',
                   'main_main_read__main_select_4567__resultset_size_count': '6666',
                   'main_main_read__main_select_4567__resultset_size_min': '0',
                   'main_main_read__main_select_4567__resultset_size_max': '10',
                   'main_main_read__main_select_4567__resultset_size_mean': '5.45',
                   'main_main_read__main_select_4567__resultset_size_stddev': '2.83',
                   'main_main_read__main_select_4567__resultset_size_median': '5.00',
                   'main_main_read__main_select_4567__resultset_size_p75': '8.00',
                   'main_main_read__main_select_4567__resultset_size_p95': '10.00',
                   'main_main_read__main_select_4567__resultset_size_p98': '10.00',
                   'main_main_read__main_select_4567__resultset_size_p99': '10.00',
                   'main_main_read__main_select_4567__resultset_size_p999': '10.00',
                   'main_main_read__main_select_all__resultset_size_count': '6666',
                   'main_main_read__main_select_all__resultset_size_min': '0',
                   'main_main_read__main_select_all__resultset_size_max': '10',
                   'main_main_read__main_select_all__resultset_size_mean': '5.43',
                   'main_main_read__main_select_all__resultset_size_stddev': '2.87',
                   'main_main_read__main_select_all__resultset_size_median': '5.00',
                   'main_main_read__main_select_all__resultset_size_p75': '8.00',
                   'main_main_read__main_select_all__resultset_size_p95': '10.00',
                   'main_main_read__main_select_all__resultset_size_p98': '10.00',
                   'main_main_read__main_select_all__resultset_size_p99': '10.00',
                   'main_main_read__main_select_all__resultset_size_p999': '10.00',
                   'main_main_write__main_write__resultset_size_count': '53328',
                   'main_main_write__main_write__resultset_size_min': '0',
                   'main_main_write__main_write__resultset_size_max': '0',
                   'main_main_write__main_write__resultset_size_mean': '0.00',
                   'main_main_write__main_write__resultset_size_stddev': '0.00',
                   'main_main_write__main_write__resultset_size_median': '0.00',
                   'main_main_write__main_write__resultset_size_p75': '0.00',
                   'main_main_write__main_write__resultset_size_p95': '0.00',
                   'main_main_write__main_write__resultset_size_p98': '0.00',
                   'main_main_write__main_write__resultset_size_p99': '0.00',
                   'main_main_write__main_write__resultset_size_p999': '0.00', 'main_resultset_size_count': '99990',
                   'main_resultset_size_min': '0', 'main_resultset_size_max': '10', 'main_resultset_size_mean': '2.37',
                   'main_resultset_size_stddev': '3.23', 'main_resultset_size_median': '0.00',
                   'main_resultset_size_p75': '5.00', 'main_resultset_size_p95': '9.00',
                   'main_resultset_size_p98': '10.00', 'main_resultset_size_p99': '10.00',
                   'main_resultset_size_p999': '10.00', 'main_skipped_tokens_count': '0',
                   'main_skipped_tokens_min': '0', 'main_skipped_tokens_max': '0', 'main_skipped_tokens_mean': '0.00',
                   'main_skipped_tokens_stddev': '0.00', 'main_skipped_tokens_median': '0.00',
                   'main_skipped_tokens_p75': '0.00', 'main_skipped_tokens_p95': '0.00',
                   'main_skipped_tokens_p98': '0.00', 'main_skipped_tokens_p99': '0.00',
                   'main_skipped_tokens_p999': '0.00', 'main_tries_count': '99990', 'main_tries_min': '0',
                   'main_tries_max': '0', 'main_tries_mean': '0.00', 'main_tries_stddev': '0.00',
                   'main_tries_median': '0.00', 'main_tries_p75': '0.00', 'main_tries_p95': '0.00',
                   'main_tries_p98': '0.00', 'main_tries_p99': '0.00', 'main_tries_p999': '0.00',
                   'rampup_rampup__rampup_insert__resultset_size_count': '10000',
                   'rampup_rampup__rampup_insert__resultset_size_min': '0',
                   'rampup_rampup__rampup_insert__resultset_size_max': '0',
                   'rampup_rampup__rampup_insert__resultset_size_mean': '0.00',
                   'rampup_rampup__rampup_insert__resultset_size_stddev': '0.00',
                   'rampup_rampup__rampup_insert__resultset_size_median': '0.00',
                   'rampup_rampup__rampup_insert__resultset_size_p75': '0.00',
                   'rampup_rampup__rampup_insert__resultset_size_p95': '0.00',
                   'rampup_rampup__rampup_insert__resultset_size_p98': '0.00',
                   'rampup_rampup__rampup_insert__resultset_size_p99': '0.00',
                   'rampup_rampup__rampup_insert__resultset_size_p999': '0.00', 'rampup_resultset_size_count': '10000',
                   'rampup_resultset_size_min': '0', 'rampup_resultset_size_max': '0',
                   'rampup_resultset_size_mean': '0.00', 'rampup_resultset_size_stddev': '0.00',
                   'rampup_resultset_size_median': '0.00', 'rampup_resultset_size_p75': '0.00',
                   'rampup_resultset_size_p95': '0.00', 'rampup_resultset_size_p98': '0.00',
                   'rampup_resultset_size_p99': '0.00', 'rampup_resultset_size_p999': '0.00',
                   'rampup_skipped_tokens_count': '0', 'rampup_skipped_tokens_min': '0',
                   'rampup_skipped_tokens_max': '0', 'rampup_skipped_tokens_mean': '0.00',
                   'rampup_skipped_tokens_stddev': '0.00', 'rampup_skipped_tokens_median': '0.00',
                   'rampup_skipped_tokens_p75': '0.00', 'rampup_skipped_tokens_p95': '0.00',
                   'rampup_skipped_tokens_p98': '0.00', 'rampup_skipped_tokens_p99': '0.00',
                   'rampup_skipped_tokens_p999': '0.00', 'rampup_tries_count': '10000', 'rampup_tries_min': '0',
                   'rampup_tries_max': '0', 'rampup_tries_mean': '0.00', 'rampup_tries_stddev': '0.00',
                   'rampup_tries_median': '0.00', 'rampup_tries_p75': '0.00', 'rampup_tries_p95': '0.00',
                   'rampup_tries_p98': '0.00', 'rampup_tries_p99': '0.00', 'rampup_tries_p999': '0.00',
                   'schema_resultset_size_count': '2', 'schema_resultset_size_min': '0',
                   'schema_resultset_size_max': '0', 'schema_resultset_size_mean': '0.00',
                   'schema_resultset_size_stddev': '0.00', 'schema_resultset_size_median': '0.00',
                   'schema_resultset_size_p75': '0.00', 'schema_resultset_size_p95': '0.00',
                   'schema_resultset_size_p98': '0.00', 'schema_resultset_size_p99': '0.00',
                   'schema_resultset_size_p999': '0.00', 'schema_schema__create_keyspace__resultset_size_count': '1',
                   'schema_schema__create_keyspace__resultset_size_min': '0',
                   'schema_schema__create_keyspace__resultset_size_max': '0',
                   'schema_schema__create_keyspace__resultset_size_mean': '0.00',
                   'schema_schema__create_keyspace__resultset_size_stddev': '0.00',
                   'schema_schema__create_keyspace__resultset_size_median': '0.00',
                   'schema_schema__create_keyspace__resultset_size_p75': '0.00',
                   'schema_schema__create_keyspace__resultset_size_p95': '0.00',
                   'schema_schema__create_keyspace__resultset_size_p98': '0.00',
                   'schema_schema__create_keyspace__resultset_size_p99': '0.00',
                   'schema_schema__create_keyspace__resultset_size_p999': '0.00',
                   'schema_schema__create_table__resultset_size_count': '1',
                   'schema_schema__create_table__resultset_size_min': '0',
                   'schema_schema__create_table__resultset_size_max': '0',
                   'schema_schema__create_table__resultset_size_mean': '0.00',
                   'schema_schema__create_table__resultset_size_stddev': '0.00',
                   'schema_schema__create_table__resultset_size_median': '0.00',
                   'schema_schema__create_table__resultset_size_p75': '0.00',
                   'schema_schema__create_table__resultset_size_p95': '0.00',
                   'schema_schema__create_table__resultset_size_p98': '0.00',
                   'schema_schema__create_table__resultset_size_p99': '0.00',
                   'schema_schema__create_table__resultset_size_p999': '0.00', 'schema_skipped_tokens_count': '0',
                   'schema_skipped_tokens_min': '0', 'schema_skipped_tokens_max': '0',
                   'schema_skipped_tokens_mean': '0.00', 'schema_skipped_tokens_stddev': '0.00',
                   'schema_skipped_tokens_median': '0.00', 'schema_skipped_tokens_p75': '0.00',
                   'schema_skipped_tokens_p95': '0.00', 'schema_skipped_tokens_p98': '0.00',
                   'schema_skipped_tokens_p99': '0.00', 'schema_skipped_tokens_p999': '0.00', 'schema_tries_count': '2',
                   'schema_tries_min': '0', 'schema_tries_max': '0', 'schema_tries_mean': '0.00',
                   'schema_tries_stddev': '0.00', 'schema_tries_median': '0.00', 'schema_tries_p75': '0.00',
                   'schema_tries_p95': '0.00', 'schema_tries_p98': '0.00', 'schema_tries_p99': '0.00',
                   'schema_tries_p999': '0.00'},
    'meters': {'main_rows_count': '252531', 'main_rows_mean_rate': '69124.79', 'main_rows_1_minute_rate': '0.00',
               'main_rows_5_minute_rate': '0.00', 'main_rows_15_minute_rate': '0.00', 'rampup_rows_count': '0',
               'rampup_rows_mean_rate': '0.00', 'rampup_rows_1_minute_rate': '0.00',
               'rampup_rows_5_minute_rate': '0.00', 'rampup_rows_15_minute_rate': '0.00', 'schema_rows_count': '0',
               'schema_rows_mean_rate': '0.00', 'schema_rows_1_minute_rate': '0.00',
               'schema_rows_5_minute_rate': '0.00', 'schema_rows_15_minute_rate': '0.00'},
    'timers': {'main_cycles_servicetime_count': '99990', 'main_cycles_servicetime_mean_rate': '27059.54',
               'main_cycles_servicetime_1_minute_rate': '0.00', 'main_cycles_servicetime_5_minute_rate': '0.00',
               'main_cycles_servicetime_15_minute_rate': '0.00', 'main_cycles_servicetime_min': '538.17',
               'main_cycles_servicetime_max': '33104.92', 'main_cycles_servicetime_mean': '2297.41',
               'main_cycles_servicetime_stddev': '2507.20', 'main_cycles_servicetime_median': '1456.52',
               'main_cycles_servicetime_p75': '2557.92', 'main_cycles_servicetime_p95': '7085.39',
               'main_cycles_servicetime_p98': '10449.58', 'main_cycles_servicetime_p99': '12731.40',
               'main_cycles_servicetime_p999': '20934.40', 'main_main_read__main_select__error_count': '0',
               'main_main_read__main_select__error_mean_rate': '0.00',
               'main_main_read__main_select__error_1_minute_rate': '0.00',
               'main_main_read__main_select__error_5_minute_rate': '0.00',
               'main_main_read__main_select__error_15_minute_rate': '0.00',
               'main_main_read__main_select__error_min': '0.00', 'main_main_read__main_select__error_max': '0.00',
               'main_main_read__main_select__error_mean': '0.00', 'main_main_read__main_select__error_stddev': '0.00',
               'main_main_read__main_select__error_median': '0.00', 'main_main_read__main_select__error_p75': '0.00',
               'main_main_read__main_select__error_p95': '0.00', 'main_main_read__main_select__error_p98': '0.00',
               'main_main_read__main_select__error_p99': '0.00', 'main_main_read__main_select__error_p999': '0.00',
               'main_main_read__main_select__success_count': '6666',
               'main_main_read__main_select__success_mean_rate': '1747.46',
               'main_main_read__main_select__success_1_minute_rate': '0.00',
               'main_main_read__main_select__success_5_minute_rate': '0.00',
               'main_main_read__main_select__success_15_minute_rate': '0.00',
               'main_main_read__main_select__success_min': '579.90',
               'main_main_read__main_select__success_max': '47798.20',
               'main_main_read__main_select__success_mean': '2626.33',
               'main_main_read__main_select__success_stddev': '2929.14',
               'main_main_read__main_select__success_median': '1714.70',
               'main_main_read__main_select__success_p75': '2866.48',
               'main_main_read__main_select__success_p95': '7615.92',
               'main_main_read__main_select__success_p98': '11332.43',
               'main_main_read__main_select__success_p99': '12549.06',
               'main_main_read__main_select__success_p999': '21824.21', 'main_main_write__main_write__error_count': '0',
               'main_main_write__main_write__error_mean_rate': '0.00',
               'main_main_write__main_write__error_1_minute_rate': '0.00',
               'main_main_write__main_write__error_5_minute_rate': '0.00',
               'main_main_write__main_write__error_15_minute_rate': '0.00',
               'main_main_write__main_write__error_min': '0.00', 'main_main_write__main_write__error_max': '0.00',
               'main_main_write__main_write__error_mean': '0.00', 'main_main_write__main_write__error_stddev': '0.00',
               'main_main_write__main_write__error_median': '0.00', 'main_main_write__main_write__error_p75': '0.00',
               'main_main_write__main_write__error_p95': '0.00', 'main_main_write__main_write__error_p98': '0.00',
               'main_main_write__main_write__error_p99': '0.00', 'main_main_write__main_write__error_p999': '0.00',
               'main_main_write__main_write__success_count': '53328',
               'main_main_write__main_write__success_mean_rate': '14005.90',
               'main_main_write__main_write__success_1_minute_rate': '0.00',
               'main_main_write__main_write__success_5_minute_rate': '0.00',
               'main_main_write__main_write__success_15_minute_rate': '0.00',
               'main_main_write__main_write__success_min': '504.03',
               'main_main_write__main_write__success_max': '29929.87',
               'main_main_write__main_write__success_mean': '2100.33',
               'main_main_write__main_write__success_stddev': '2441.00',
               'main_main_write__main_write__success_median': '1315.35',
               'main_main_write__main_write__success_p75': '2291.45',
               'main_main_write__main_write__success_p95': '6523.84',
               'main_main_write__main_write__success_p98': '10014.48',
               'main_main_write__main_write__success_p99': '12609.14',
               'main_main_write__main_write__success_p999': '23775.68', 'main_read_input_count': '6746',
               'main_read_input_mean_rate': '1819.55', 'main_read_input_1_minute_rate': '0.00',
               'main_read_input_5_minute_rate': '0.00', 'main_read_input_15_minute_rate': '0.00',
               'main_read_input_min': '0.09', 'main_read_input_max': '28.44', 'main_read_input_mean': '0.62',
               'main_read_input_stddev': '1.95', 'main_read_input_median': '0.34', 'main_read_input_p75': '0.44',
               'main_read_input_p95': '0.97', 'main_read_input_p98': '3.23', 'main_read_input_p99': '11.58',
               'main_read_input_p999': '26.10', 'main_result_count': '99990', 'main_result_mean_rate': '26971.48',
               'main_result_1_minute_rate': '0.00', 'main_result_5_minute_rate': '0.00',
               'main_result_15_minute_rate': '0.00', 'main_result_min': '506.00', 'main_result_max': '30137.13',
               'main_result_mean': '2238.43', 'main_result_stddev': '2509.04', 'main_result_median': '1382.84',
               'main_result_p75': '2440.71', 'main_result_p95': '7559.85', 'main_result_p98': '9853.45',
               'main_result_p99': '12120.49', 'main_result_p999': '24447.76', 'main_result_success_count': '99990',
               'main_result_success_mean_rate': '26966.72', 'main_result_success_1_minute_rate': '0.00',
               'main_result_success_5_minute_rate': '0.00', 'main_result_success_15_minute_rate': '0.00',
               'main_result_success_min': '546.12', 'main_result_success_max': '22183.55',
               'main_result_success_mean': '2316.52', 'main_result_success_stddev': '2509.53',
               'main_result_success_median': '1411.22', 'main_result_success_p75': '2552.26',
               'main_result_success_p95': '7126.78', 'main_result_success_p98': '10873.03',
               'main_result_success_p99': '12747.74', 'main_result_success_p999': '21945.07',
               'main_strides_servicetime_count': '6666', 'main_strides_servicetime_mean_rate': '1796.73',
               'main_strides_servicetime_1_minute_rate': '0.00', 'main_strides_servicetime_5_minute_rate': '0.00',
               'main_strides_servicetime_15_minute_rate': '0.00', 'main_strides_servicetime_min': '17564.47',
               'main_strides_servicetime_max': '108127.42', 'main_strides_servicetime_mean': '39817.71',
               'main_strides_servicetime_stddev': '13228.14', 'main_strides_servicetime_median': '36135.07',
               'main_strides_servicetime_p75': '46573.84', 'main_strides_servicetime_p95': '66025.30',
               'main_strides_servicetime_p98': '71968.22', 'main_strides_servicetime_p99': '79617.56',
               'main_strides_servicetime_p999': '107807.84'}}
EXPECTED_ABRIDGED_REPORT = {'histograms': {'main_main_read__main_select_all__resultset_size_count': '6666',
                                           'main_main_read__main_select_all__resultset_size_max': '10',
                                           'main_main_read__main_select_all__resultset_size_mean': '5.43',
                                           'main_main_read__main_select_all__resultset_size_median': '5.00',
                                           'main_main_read__main_select_all__resultset_size_min': '0',
                                           'main_main_read__main_select_all__resultset_size_p75': '8.00',
                                           'main_main_read__main_select_all__resultset_size_p95': '10.00',
                                           'main_main_read__main_select_all__resultset_size_p98': '10.00',
                                           'main_main_read__main_select_all__resultset_size_p99': '10.00',
                                           'main_main_read__main_select_all__resultset_size_p999': '10.00',
                                           'main_main_read__main_select_all__resultset_size_stddev': '2.87'},
                            'timers': {'main_cycles_servicetime_15_minute_rate': '0.00',
                                       'main_cycles_servicetime_1_minute_rate': '0.00',
                                       'main_cycles_servicetime_5_minute_rate': '0.00',
                                       'main_cycles_servicetime_count': '99990',
                                       'main_cycles_servicetime_max': '33104.92',
                                       'main_cycles_servicetime_mean': '2297.41',
                                       'main_cycles_servicetime_mean_rate': '27059.54',
                                       'main_cycles_servicetime_median': '1456.52',
                                       'main_cycles_servicetime_min': '538.17',
                                       'main_cycles_servicetime_p75': '2557.92',
                                       'main_cycles_servicetime_p95': '7085.39',
                                       'main_cycles_servicetime_p98': '10449.58',
                                       'main_cycles_servicetime_p99': '12731.40',
                                       'main_cycles_servicetime_p999': '20934.40',
                                       'main_cycles_servicetime_stddev': '2507.20',
                                       'main_main_read__main_select__error_15_minute_rate': '0.00',
                                       'main_main_read__main_select__error_1_minute_rate': '0.00',
                                       'main_main_read__main_select__error_5_minute_rate': '0.00',
                                       'main_main_read__main_select__error_count': '0',
                                       'main_main_read__main_select__error_max': '0.00',
                                       'main_main_read__main_select__error_mean': '0.00',
                                       'main_main_read__main_select__error_mean_rate': '0.00',
                                       'main_main_read__main_select__error_median': '0.00',
                                       'main_main_read__main_select__error_min': '0.00',
                                       'main_main_read__main_select__error_p75': '0.00',
                                       'main_main_read__main_select__error_p95': '0.00',
                                       'main_main_read__main_select__error_p98': '0.00',
                                       'main_main_read__main_select__error_p99': '0.00',
                                       'main_main_read__main_select__error_p999': '0.00',
                                       'main_main_read__main_select__error_stddev': '0.00',
                                       'main_main_read__main_select__success_15_minute_rate': '0.00',
                                       'main_main_read__main_select__success_1_minute_rate': '0.00',
                                       'main_main_read__main_select__success_5_minute_rate': '0.00',
                                       'main_main_read__main_select__success_count': '6666',
                                       'main_main_read__main_select__success_max': '47798.20',
                                       'main_main_read__main_select__success_mean': '2626.33',
                                       'main_main_read__main_select__success_mean_rate': '1747.46',
                                       'main_main_read__main_select__success_median': '1714.70',
                                       'main_main_read__main_select__success_min': '579.90',
                                       'main_main_read__main_select__success_p75': '2866.48',
                                       'main_main_read__main_select__success_p95': '7615.92',
                                       'main_main_read__main_select__success_p98': '11332.43',
                                       'main_main_read__main_select__success_p99': '12549.06',
                                       'main_main_read__main_select__success_p999': '21824.21',
                                       'main_main_read__main_select__success_stddev': '2929.14',
                                       'main_main_write__main_write__error_15_minute_rate': '0.00',
                                       'main_main_write__main_write__error_1_minute_rate': '0.00',
                                       'main_main_write__main_write__error_5_minute_rate': '0.00',
                                       'main_main_write__main_write__error_count': '0',
                                       'main_main_write__main_write__error_max': '0.00',
                                       'main_main_write__main_write__error_mean': '0.00',
                                       'main_main_write__main_write__error_mean_rate': '0.00',
                                       'main_main_write__main_write__error_median': '0.00',
                                       'main_main_write__main_write__error_min': '0.00',
                                       'main_main_write__main_write__error_p75': '0.00',
                                       'main_main_write__main_write__error_p95': '0.00',
                                       'main_main_write__main_write__error_p98': '0.00',
                                       'main_main_write__main_write__error_p99': '0.00',
                                       'main_main_write__main_write__error_p999': '0.00',
                                       'main_main_write__main_write__error_stddev': '0.00',
                                       'main_main_write__main_write__success_15_minute_rate': '0.00',
                                       'main_main_write__main_write__success_1_minute_rate': '0.00',
                                       'main_main_write__main_write__success_5_minute_rate': '0.00',
                                       'main_main_write__main_write__success_count': '53328',
                                       'main_main_write__main_write__success_max': '29929.87',
                                       'main_main_write__main_write__success_mean': '2100.33',
                                       'main_main_write__main_write__success_mean_rate': '14005.90',
                                       'main_main_write__main_write__success_median': '1315.35',
                                       'main_main_write__main_write__success_min': '504.03',
                                       'main_main_write__main_write__success_p75': '2291.45',
                                       'main_main_write__main_write__success_p95': '6523.84',
                                       'main_main_write__main_write__success_p98': '10014.48',
                                       'main_main_write__main_write__success_p99': '12609.14',
                                       'main_main_write__main_write__success_p999': '23775.68',
                                       'main_main_write__main_write__success_stddev': '2441.00',
                                       'main_result_15_minute_rate': '0.00',
                                       'main_result_1_minute_rate': '0.00',
                                       'main_result_5_minute_rate': '0.00',
                                       'main_result_count': '99990',
                                       'main_result_max': '30137.13',
                                       'main_result_mean': '2238.43',
                                       'main_result_mean_rate': '26971.48',
                                       'main_result_median': '1382.84',
                                       'main_result_min': '506.00',
                                       'main_result_p75': '2440.71',
                                       'main_result_p95': '7559.85',
                                       'main_result_p98': '9853.45',
                                       'main_result_p99': '12120.49',
                                       'main_result_p999': '24447.76',
                                       'main_result_stddev': '2509.04',
                                       'main_result_success_15_minute_rate': '0.00',
                                       'main_result_success_1_minute_rate': '0.00',
                                       'main_result_success_5_minute_rate': '0.00',
                                       'main_result_success_count': '99990',
                                       'main_result_success_max': '22183.55',
                                       'main_result_success_mean': '2316.52',
                                       'main_result_success_mean_rate': '26966.72',
                                       'main_result_success_median': '1411.22',
                                       'main_result_success_min': '546.12',
                                       'main_result_success_p75': '2552.26',
                                       'main_result_success_p95': '7126.78',
                                       'main_result_success_p98': '10873.03',
                                       'main_result_success_p99': '12747.74',
                                       'main_result_success_p999': '21945.07',
                                       'main_result_success_stddev': '2509.53',
                                       'main_strides_servicetime_15_minute_rate': '0.00',
                                       'main_strides_servicetime_1_minute_rate': '0.00',
                                       'main_strides_servicetime_5_minute_rate': '0.00',
                                       'main_strides_servicetime_count': '6666',
                                       'main_strides_servicetime_max': '108127.42',
                                       'main_strides_servicetime_mean': '39817.71',
                                       'main_strides_servicetime_mean_rate': '1796.73',
                                       'main_strides_servicetime_median': '36135.07',
                                       'main_strides_servicetime_min': '17564.47',
                                       'main_strides_servicetime_p75': '46573.84',
                                       'main_strides_servicetime_p95': '66025.30',
                                       'main_strides_servicetime_p98': '71968.22',
                                       'main_strides_servicetime_p99': '79617.56',
                                       'main_strides_servicetime_p999': '107807.84',
                                       'main_strides_servicetime_stddev': '13228.14'}}


@pytest.fixture(scope="module")
def es_test_doc() -> dict:
    with ES_TEST_DOC_FP.open(mode="r") as infile:
        return json.load(infile)


@pytest.fixture(scope="module")
def es_filtered_test_results() -> dict:
    with ES_FILTERED_TEST_RESULTS_FP.open(mode="r") as infile:
        return json.load(infile)


@pytest.fixture(scope="module")
def nb_analyzer(nb_analyzer_args: NoSQLBenchAnalyzerArgs) \
        -> Generator[NoSQLBenchResultsAnalyzer, None, None]:
    yield NoSQLBenchResultsAnalyzer(nb_analyzer_args)


class TestNoSQLBenchResultsAnalyzer:
    @pytest.fixture(scope="function")
    def nb_report_builder(self) -> Generator[NoSQLBenchReportBuilder, None, None]:
        yield NoSQLBenchReportBuilder(NB_SUMMARY_FP)

    @pytest.fixture(scope="function")
    def nb_analyzer_args(self,
                         nb_report_builder: NoSQLBenchReportBuilder) -> Generator[NoSQLBenchAnalyzerArgs, None, None]:
        yield NoSQLBenchAnalyzerArgs(
            test_id="mock_test_id",
            es_index="mock_es_index",
            es_doc_type="test_stats",
            events={},
            email_recipients=["nobody@nowhere.none"],
            is_gce=False,
            use_wide_query=True
        )

    def test_nb_report_builder_full_report(self, nb_report_builder: NoSQLBenchReportBuilder):
        nb_report_builder.build_full_report()
        full_report = nb_report_builder.full_report

        with soft_assertions():
            for section in full_report:
                for key in full_report[section]:
                    assert_that(full_report[section][key])\
                        .is_equal_to(EXPECTED_FULL_REPORT[section][key])

    def test_nb_report_builder_abridged_report(self, nb_report_builder: NoSQLBenchReportBuilder):
        nb_report_builder.build_abridged_report()
        abridged_report = nb_report_builder.abridged_report

        with soft_assertions():
            for section in abridged_report:
                for key in abridged_report[section]:
                    assert_that(abridged_report[section][key])\
                        .is_equal_to(EXPECTED_ABRIDGED_REPORT[section][key])


class TestNoSQLBenchMetricComparator:
    COMPARISON_AXIS = [
        ComparisonAxis(name="main_cycles_servicetime_median", smaller_is_better=True),
        ComparisonAxis(name="main_cycles_servicetime_mean_rate", smaller_is_better=False),
        ComparisonAxis(name="main_cycles_servicetime_max", smaller_is_better=True),
        ComparisonAxis(name='main_cycles_servicetime_min', smaller_is_better=True),
        ComparisonAxis(name='main_cycles_servicetime_p95', smaller_is_better=True),
        ComparisonAxis(name='main_cycles_servicetime_p99', smaller_is_better=True),
        ComparisonAxis(name='main_result_mean_rate', smaller_is_better=False)
    ]
    EXPECTED_VALUES_LAST_RUN = {'main_cycles_servicetime_max': {'current_value': '21847.27',
                                                                'diff': -46651.39,
                                                                'last_run_time_completed': '2021-11-22 10:03',
                                                                'last_value': 68498.66},
                                'main_cycles_servicetime_mean_rate': {'current_value': '26261.69',
                                                                      'diff': 577.7999999999993,
                                                                      'last_run_time_completed': '2021-11-22 '
                                                                                                 '10:03',
                                                                      'last_value': 25683.89},
                                'main_cycles_servicetime_median': {'current_value': '1433.74',
                                                                   'diff': 6.9500000000000455,
                                                                   'last_run_time_completed': '2021-11-22 '
                                                                                              '10:03',
                                                                   'last_value': 1426.79},
                                'main_cycles_servicetime_min': {'current_value': '455.59',
                                                                'diff': -27.960000000000036,
                                                                'last_run_time_completed': '2021-11-22 10:03',
                                                                'last_value': 483.55},
                                'main_cycles_servicetime_p95': {'current_value': '7520.34',
                                                                'diff': -138.34999999999945,
                                                                'last_run_time_completed': '2021-11-22 10:03',
                                                                'last_value': 7658.69},
                                'main_cycles_servicetime_p99': {'current_value': '15091.28',
                                                                'diff': 677.8600000000006,
                                                                'last_run_time_completed': '2021-11-22 10:03',
                                                                'last_value': 14413.42},
                                'main_result_mean_rate': {'current_value': '26166.21',
                                                          'diff': 613.9500000000007,
                                                          'last_run_time_completed': '2021-11-22 10:03',
                                                          'last_value': 25552.26}}
    EXPECTED_VALUES_HISTORY = {
        'main_cycles_servicetime_median': {'current': 1470.1, 'version_best': 1433.74, 'diff_best': 36.3599999999999,
                                           'delta_best_percent': 2.5416856959111134,
                                           'diff_time_completed': '2021-11-20 01:25', 'diff_mean': 3.1933333333336122,
                                           'status': 'Regression'},
        'main_cycles_servicetime_mean_rate': {'current': 25683.89, 'version_best': 26261.69,
                                              'diff_best': -577.7999999999993, 'delta_best_percent': -2.198637527130194,
                                              'diff_time_completed': '2021-11-22 10:03',
                                              'diff_mean': -18.22166666666817, 'status': 'Regression'},
        'main_cycles_servicetime_max': {'current': 68498.66, 'version_best': 21847.27, 'diff_best': 46651.39,
                                        'delta_best_percent': 151.9499087269143,
                                        'diff_time_completed': '2021-11-22 10:03', 'diff_mean': -8854.551666666666,
                                        'status': 'Regression'},
        'main_cycles_servicetime_min': {'current': 538.17, 'version_best': 455.59, 'diff_best': 82.57999999999998,
                                        'delta_best_percent': 16.674182410467296,
                                        'diff_time_completed': '2021-11-22 11:42', 'diff_mean': -39.666666666666686,
                                        'status': 'Regression'},
        'main_cycles_servicetime_p95': {'current': 8064.98, 'version_best': 7520.34, 'diff_best': 544.6399999999994,
                                        'delta_best_percent': 7.228501510030029,
                                        'diff_time_completed': '2021-11-20 01:25', 'diff_mean': -14.27833333333274,
                                        'status': 'Regression'},
        'main_cycles_servicetime_p99': {'current': 15091.28, 'version_best': 15091.28, 'diff_best': 0.0,
                                        'delta_best_percent': 0.0, 'diff_time_completed': '2021-11-19 22:51',
                                        'diff_mean': 1219.8583333333336, 'status': 'Regression'},
        'main_result_mean_rate': {'current': 25552.26, 'version_best': 26166.21, 'diff_best': -613.9500000000007,
                                  'delta_best_percent': -2.3452678394300435, 'diff_time_completed': '2021-11-22 10:03',
                                  'diff_mean': -12.036666666670499, 'status': 'Regression'}}

    @pytest.fixture(scope="function")
    def nb_metric_comparator(self,
                             es_test_doc: dict,
                             es_filtered_test_results: dict) -> Generator[MetricComparator, None, None]:

        yield MetricComparator(
            current_test_results=es_test_doc,
            filtered_test_results=es_filtered_test_results,
            comparison_axis=self.COMPARISON_AXIS
        )

    def test_nb_metric_comparator_last_run_comparison(self, nb_metric_comparator: MetricComparator):
        vs_last = nb_metric_comparator.vs_last
        pprint(vs_last)

        with soft_assertions():
            assert_that(vs_last).contains_key(*self.EXPECTED_VALUES_LAST_RUN.keys())
            for key, value in self.EXPECTED_VALUES_LAST_RUN.items():
                assert_that(value).contains_key(*self.EXPECTED_VALUES_LAST_RUN[key].keys())
                for sub_key, sub_value in value.items():
                    assert_that(self.EXPECTED_VALUES_LAST_RUN[key][sub_key]).is_equal_to(sub_value)

    def test_nb_metric_comparator_version_history_comparison(self, nb_metric_comparator: MetricComparator):
        vs_history = nb_metric_comparator.vs_history
        pprint(vs_history)

        with soft_assertions():
            assert_that(vs_history).contains_key(*self.EXPECTED_VALUES_HISTORY.keys())
            for key, value in self.EXPECTED_VALUES_HISTORY.items():
                assert_that(value).contains_key(*self.EXPECTED_VALUES_HISTORY[key].keys())
                for sub_key, sub_value in value.items():
                    assert_that(self.EXPECTED_VALUES_HISTORY[key][sub_key]).is_equal_to(sub_value)
