{
 "title": "Gemini",
 "tags": [
  "gemini",
  "go",
  "go-runtime"
 ],
 "time": { "from": "2025-12-04T15:59:09.392Z", "to": "2025-12-04T16:26:48.767Z" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values(gemini_stmt_error_last_timestamp_seconds,table)"
    }
   },
   {
    "name": "stmt_storage",
    "label": "Statement Logger Storage",
    "query": {
     "query": "label_values(gemini_stmt_error_last_timestamp_seconds,stmt_storage)"
    }
   },
   {
    "name": "partitions",
    "label": "Partition Hashes",
    "query": {
     "query": "label_values(gemini_stmt_error_last_timestamp_seconds, partition_hash)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Gemini", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gemini_execution_errors > 0", "legendFormat": "{{ty}}" }
   ]
  },
  {
   "title": "RealTime Errors",
   "type": "table",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "gemini_stmt_error_last_timestamp_seconds{table=\"$table\", partition_hash=~\"$partitions\", stmt_storage=~\"$stmt_storage\"}\n"
    }
   ]
  },
  {
   "title": "Validated Rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (table) (rate(gemini_validated_rows[$interval]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Validated Rows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (table) (gemini_validated_rows)",
     "legendFormat": "{{table}}"
    },
    {
     "expr": "gemini_cql_queries{cluster=\"oracle\", query_type=~\"SelectStatement|SelectMultiPartition|SelectRangeStatement|SelectMultiPartitionRangeStatement|SelectByIndexStatement|SelectFromMaterializedViewStatement\"} > 0",
     "legendFormat": "{{query_type}}"
    }
   ]
  },
  {
   "title": "Function Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(gemini_execution_time_sum[$interval]) / rate(gemini_execution_time_count[$interval])",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Function Execution Time P(50,95,99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(gemini_execution_time_bucket[$interval]))",
     "legendFormat": "P50 {{task}}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(gemini_execution_time_bucket[$interval]))",
     "legendFormat": "P95 {{task}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(gemini_execution_time_bucket[$interval]))",
     "legendFormat": "P99 {{task}}"
    }
   ]
  },
  {
   "title": "Statement Logger Items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    { "expr": "gemini_statement_logger_items", "legendFormat": "Number Of Items in Queue" },
    {
     "expr": "rate(gemini_statement_logger_enqueued_total[$interval])",
     "legendFormat": "Pushed"
    },
    {
     "expr": "rate(gemini_statement_logger_dequeued_total[$interval])",
     "legendFormat": "Popped"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gemini_workers_current", "legendFormat": "{{exported_job}}" }
   ]
  },
  {
   "title": "Number of Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(gemini_execution_time_count[$interval])) by (instance, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  { "title": "CQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Query Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(gemini_cql_query_time_sum{cluster=~\"$cluster\"}[$interval])\n/\nrate(gemini_cql_query_time_count{cluster=~\"$cluster\"}[$interval]) > 0",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(gemini_cql_query_errors{cluster=~\"$cluster\"}[$interval]) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CQL Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(gemini_cql_requests{system=~\"$cluster\"}[$interval]) > 0",
     "legendFormat": "{{system}} - {{method}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 13, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(gemini_cql_requests{system=~\"$cluster\"}[$interval]))",
     "legendFormat": "Total Sent"
    }
   ]
  },
  {
   "title": "Requests per Type",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(system,method) (rate(gemini_cql_requests{system=~\"$cluster\"}[$interval])) > 0",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Error percentage Per System",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Error percentage per system\n(\n  sum by(system) (rate(gemini_cql_error_requests{cluster=~\"$cluster\"}[$interval]))\n  / \n  sum by(system) (rate(gemini_cql_requests{cluster=~\"$cluster\"}[$interval]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Per System",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(system) (rate(gemini_cql_error_requests{cluster=~\"$cluster\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Timeouts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(system,query_type) (rate(gemini_cql_query_timeouts{cluster=~\"$cluster\"}[$interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemini_cql_connections{cluster=~\"$cluster\"} > 0",
     "legendFormat": "Per host {{cluster}} {{host}}"
    },
    {
     "expr": "sum by(cluster) (gemini_cql_connections{cluster=~\"$cluster\"}) > 0",
     "legendFormat": "Connections per cluster {{cluster}}"
    }
   ]
  },
  {
   "title": "Connection errors per Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum by(cluster, host) (rate(gemini_cql_connections_errors{cluster=~\"$cluster\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "rate(gemini_cql_connect_time_sum{cluster=~\"$cluster\"}[$interval])\n/\nrate(gemini_cql_connect_time_count{cluster=~\"$cluster\"}[$interval])",
     "legendFormat": "AVG Conn Time {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum by(cluster, host, le) (\n    rate(gemini_cql_connect_time_bucket{cluster=\"$cluster\"}[$interval])\n  )\n)\n",
     "legendFormat": "P95 {{host}} {{cluster}}"
    }
   ]
  },
  { "title": "Go Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "gemini_go_memstats_mspan_inuse_bytes"
    },
    {
     "expr": "gemini_go_memstats_mspan_sys_bytes"
    },
    {
     "expr": "gemini_go_memstats_mcache_inuse_bytes"
    },
    {
     "expr": "gemini_go_memstats_mcache_sys_bytes"
    },
    {
     "expr": "gemini_go_memstats_buck_hash_sys_bytes"
    },
    {
     "expr": "gemini_go_memstats_gc_sys_bytes"
    },
    {
     "expr": "gemini_go_memstats_other_sys_bytes - gemini_go_memstats_other_sys_bytes",
     "legendFormat": "bytes of memory are used for other runtime allocations"
    },
    {
     "expr": "gemini_go_memstats_next_gc_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory in In-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "gemini_go_memstats_heap_alloc_bytes"
    },
    {
     "expr": "gemini_go_memstats_heap_sys_bytes"
    },
    {
     "expr": "gemini_go_memstats_heap_idle_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemini_go_memstats_heap_inuse_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemini_go_memstats_heap_released_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "gemini_go_memstats_stack_inuse_bytes"
    },
    {
     "expr": "gemini_go_memstats_stack_sys_bytes"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "gemini_go_memstats_sys_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "gemini_go_memstats_mallocs_total - gemini_go_memstats_frees_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "rate(gemini_go_memstats_mallocs_total[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "rate(gemini_go_memstats_lookups_total[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "targets": [
    { "expr": "gemini_go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Goroutines Deriv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "deriv(gemini_go_goroutines[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(gemini_go_memstats_alloc_bytes_total[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "gemini_process_resident_memory_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemini_process_virtual_memory_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Memory Deriv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(gemini_process_resident_memory_bytes[$interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "deriv(gemini_process_virtual_memory_bytes[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Memstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "gemini_go_memstats_alloc_bytes", "legendFormat": "__auto" },
    {
     "expr": "rate(gemini_go_memstats_alloc_bytes_total[30s])",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemini_go_memstats_stack_inuse_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemini_go_memstats_heap_inuse_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 133 },
   "targets": [
    { "expr": "gemini_process_open_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Open FDs Deriv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 133 },
   "targets": [
    {
     "expr": "deriv(gemini_process_open_fds[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GO GC Duration Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "gemini_go_gc_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(gemini_process_cpu_seconds_total[$interval]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GOMAXPROCS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 141 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemini_go_sched_gomaxprocs_threads",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}