test_duration: 2160

cs_duration: '55m'
cs_user_profiles:
    - scylla-qa-internal/cust_d/templated_tables_mv.yaml

pre_create_schema: true

user_profile_table_count: 5000
batch_size: 100

n_loaders: 5
n_db_nodes: 1
add_node_cnt: 5

jmx_heap_memory: 1024 # this is a fix/workaround for https://github.com/scylladb/scylla/issues/7609

instance_type_db: 'i4i.8xlarge'
instance_type_loader: 'c6i.4xlarge'
user_prefix: 'longevity-5000-tables'
root_disk_size_runner: 120


cluster_health_check: false

nemesis_class_name: 'SisyphusMonkey'
nemesis_seed: '404'
nemesis_interval: 60

# TODO: remove when https://github.com/scylladb/scylla-tools-java/issues/175 resolved
stop_test_on_stress_failure: false
