test_duration: 2520

cs_duration: '20m'
cs_user_profiles:
    - scylla-qa-internal/cust_d/templated_tables_mv.yaml

pre_create_schema: true

user_profile_table_count: 5000
batch_size: 100

n_loaders: 3
n_monitor_nodes: 1
n_db_nodes: 1
add_node_cnt: 5

instance_type_db: 'i4i.8xlarge'
instance_type_loader: 'c6i.8xlarge'
instance_type_monitor: 'm6i.xlarge'
root_disk_size_monitor: 120
root_disk_size_runner: 120

user_prefix: 'long-5000-tables'
cluster_health_check: true

nemesis_class_name: 'SisyphusMonkey'
nemesis_seed: '404'
# NOTE: health checks will take some time, so, don't add significant waiting in this part
nemesis_interval: 3

append_scylla_yaml:
  # NOTE: https://github.com/scylladb/scylla-monitoring/issues/2429
  enable_node_aggregated_table_metrics: false
