n_db_nodes: '3 3 0'  # make n_db_nodes configured as multi-dc with last dc set to 0 (so later easily new node can be added)
region_name: 'eu-west-1 eu-west-2 eu-north-1'


n_db_zero_token_nodes: '0 0 0'
zero_token_instance_type_db: 'i4i.large'
use_zero_nodes: true
