scylla-bench:
<<<<<<< HEAD
  image: scylladb/scylla-bench:1.1.0
||||||| parent of 585d885fa (chore(deps): update scylladb/scylla-bench docker tag to v1.3.0)
  image: scylladb/scylla-bench:1.1.1
=======
  image: scylladb/scylla-bench:1.3.0
>>>>>>> 585d885fa (chore(deps): update scylladb/scylla-bench docker tag to v1.3.0)
