# Test
test_duration: 3600
prepare_write_cmd: ["cassandra-stress write no-warmup cl=QUORUM n=4000000 -schema 'replication(strategy=NetworkTopologyStrategy,replication_factor=3)' -mode cql3 native -rate threads=20 -pop seq=1..4000000 -log interval=30"]
stress_cmd: ["cassandra-stress mixed cl=QUORUM duration=48h -schema 'replication(strategy=NetworkTopologyStrategy,replication_factor=3)' -mode cql3 native -rate threads=10 -pop seq=1..4000000 -log interval=90"]
run_fullscan: ['{"mode": "table_and_aggregate", "ks_cf": "random", "interval": 30}']

pre_create_schema: true

keyspace_num: 1000
batch_size: 100

space_node_threshold: 10485760

nemesis_class_name: 'SisyphusMonkey'
nemesis_seed: '022'
nemesis_interval: 30

# Env
n_db_nodes: 6
n_loaders: 10

instance_type_db: 'i4i.8xlarge'
gce_instance_type_db: 'n2-highmem-64'
gce_n_local_ssd_disk_db: 16

root_disk_size_db: 60 # twice as as default, cause each keyspace generate lots of logs
instance_type_loader: 'c6i.4xlarge'
root_disk_size_monitor: 100
root_disk_size_runner: 120

user_prefix: 'longevity-1000-keyspaces'

# TODO: remove when https://github.com/scylladb/scylla-tools-java/issues/175 resolved
stop_test_on_stress_failure: false
use_prepared_loaders: true

use_preinstalled_scylla: true
