test_duration: 4320

cs_duration: '2m'
cs_user_profiles:
    - scylla-qa-internal/cust_d/templated_tables_mv.yaml

user_profile_table_count: 5000
batch_size: 200

n_loaders: 5
n_monitor_nodes: 1
n_db_nodes: 1
add_node_cnt: 5

instance_type_db: 'i3.4xlarge'
instance_type_loader: 'c5.2xlarge'
user_prefix: 'longevity-5000-tables'

nemesis_class_name: NoOpMonkey
nemesis_interval: 30

store_results_in_elasticsearch: False

# TODO: enable back coredump on bad_alloc
# scylla/issues/4764 was blocking progress into the production issues we were trying to reproduce
# so we temporary removed the default `--abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc`
# once the issue would be solved we can enable it back.
append_scylla_args: '--blocked-reactor-notify-ms 500'
