name: Copilot Setup Steps

# This workflow configures GitHub Copilot to run on Blacksmith runners.

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - run: echo "Copilot runs on Blacksmith runner"
