name: PR require backport label
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - master

jobs:
  label:
    if: github.event.pull_request.draft == false
    runs-on: blacksmith-2vcpu-ubuntu-2404
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "backport/none\nbackport/[\\w-]*[\\d.]*$"
          use_regex: true
          add_comment: false
