name: PR require backport label
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - master

jobs:
  label:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@23e10fde7e062233401931a0eece796cd9bf3177 # v5.6.0
        with:
          mode: minimum
          count: 1
          labels: "backport/none\nbackport/[\\w-]*[\\d.]*$"
          use_regex: true
          add_comment: false
